### PR TITLE
test

### PR DESCRIPTION
**Pull request by feons**

### CODE REVIEW

**Comment by feons** [comment]
is auth code supposed to return an array with more than 1 items?

**Comment by jhaynie** [comment]
@feons i don't believe so.

**Comment by feons** [comment]
@alasdairhurst, looking at the the travis error, there might be some issues with signing in?

**Comment by alasdairhurst** [comment]
@feons Looks like you may be right there. Google is saying there's 'suspicious activity' and wants a password reset. The way around this is to enable 2 step auth and we can't do that easily with automated testing.
Since the selenium solution doesn't seem to be very consistant i'll try and refactor it to use the beta javascript API which would probably be the better solution for this.  (the array of auth codes was one of the inconsistancies here)

@jhaynie I think for now, temporarily disabling the auth code tests that use selenium would be the best choice until I rewrite the new unit tests with the Google API (which I should probably have done to start with).

**Comment by jhaynie** [comment]
might want to switch to how i do it here: much more reliable:
https://github.com/appcelerator/appc-end-to-end/blob/master/lib/index.js#L112

**Comment by alasdairhurst** [comment]
@jhaynie  Thanks. That's SMS rather than email, although I do need an SMS test as well as an email test so I will include that too.

**Pull request closed without merging**
