### PR TITLE
[CLI-389] Add proxy option to network request if available

### PR DESCRIPTION
**Pull request by feons**
https://jira.appcelerator.org/browse/CLI-389

### CODE REVIEW

**Comment by feons** [comment]
this is weird, still trying to figure out what's wrong.

**Comment by jhaynie** [comment]
@feons i've noticed the tests have stopped working and it seems like it's the encryption key.

**Comment by feons** [comment]
@jhaynie, how can i fix it?

**Comment by jhaynie** [comment]
i'm not sure. @alasdairhurst set it up and has the magic keys :)

**Comment by feons** [comment]
@alasdairhurst please sprinkle some magic dust!

**Comment by ingo** [comment]
@jhaynie @feons @alasdairhurst I believe this is expected: http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests

For this repo, we should either come up with a different set of tests that do not require the encrypted key, or have submitters commit to branches instead.

@feons, you could try committing this to a branch and see if it passes. The PR would then be from one branch to master.

**Comment by jhaynie** [comment]
@ingo i guess that makes sense. can we come up with a generic user to do this?

**Pull request closed without merging**
