### PR TITLE
[CLI-389] Add proxy option to network request if available

### PR DESCRIPTION
**Pull request by feons**
https://jira.appcelerator.org/browse/CLI-389

### CODE REVIEW

**Comment by alasdairhurst** [comment]
@tonylukasavage @muhammaddadu  Can you understand the travis error in this build? It's something to do with the coverage (kahvesi).

**Comment by tonylukasavage** [comment]
Well, it's one of the tests called by cover. Start with the failed test and see why it might execute differently when invoked via Istanbul.

**Comment by alasdairhurst** [comment]
@feons can you merge the updated master into this branch to make sure all the tests pass please??

**Comment by ingo** [comment]
This tested fine on my local machine. Merging.

**Pull request merged**
